# Generated by Django 5.0.2 on 2024-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_ingredient_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Milliliters', 'Milliliters'), ('Liters', 'Liters'), ('Teaspoons', 'Teaspoons'), ('Tablespoons', 'Tablespoons'), ('Cups', 'Cups'), ('Ounces', 'Ounces'), ('Pounds', 'Pounds'), ('Pieces', 'Pieces'), ('Slices', 'Slices'), ('Cloves', 'Cloves'), ('Pinches', 'Pinches'), ('Handfuls', 'Handfuls'), ('Drops', 'Drops')], max_length=20),
        ),
        
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
