# Generated by Django 5.0.2 on 2024-03-10 11:52

import django.db.models.deletion
from django.db import migrations, models  


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient_optional_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
