# Generated by Django 5.0.2 on 2024-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Milliliters', 'Milliliters'), ('Liters', 'Liters'), ('Teaspoons', 'Teaspoons'), ('Tablespoons', 'Tablespoons'), ('Cups', 'Cups'), ('Ounces', 'Ounces'), ('Pounds', 'Pounds'), ('Pieces', 'Pieces'), ('Slices', 'Slices'), ('Cloves', 'Cloves'), ('Pinches', 'Pinches'), ('Handfuls', 'Handfuls'), ('Drops', 'Drops')], max_length=100),
        ),
    ]
